# Generated by Django 5.1.15 on 2026-08-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="logo",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
