# Generated by Django 5.1.15 on 2026-06-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pos_clave", models.CharField(max_length=50)),
                ("raw_name", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product aliases",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pos_clave", "raw_name"), name="unique_alias_identity"
                    )
                ],
            },
        ),
    ]
