# Generated by Django 5.1.15 on 2026-08-27 14:20

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_multitenant"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("starters", "Starters"),
                            ("mains", "Mains"),
                            ("sides", "Sides"),
                            ("desserts", "Desserts"),
                            ("alcohol", "Alcoholic drinks"),
                            ("soft", "Soft drinks"),
                            ("other", "Other"),
                        ],
                        default="starters",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quoted price, tax included",
                        max_digits=12,
                    ),
                ),
                (
                    "servings",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal(1),
                        help_text="How many guests one unit serves",
                        max_digits=6,
                    ),
                ),
                (
                    "product_units",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal(1),
                        help_text="Product units consumed by one unit of this item",
                        max_digits=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "name"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("concept", models.CharField(blank=True, max_length=200)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("guests", models.PositiveIntegerField(default=1)),
                (
                    "pricing_mode",
                    models.CharField(
                        choices=[
                            ("consumption", "By consumption"),
                            ("per_guest", "Price per guest"),
                        ],
                        default="consumption",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_guest",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=12
                    ),
                ),
                ("payment_terms", models.CharField(blank=True, max_length=200)),
                (
                    "tip_rate",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.10"), max_digits=4
                    ),
                ),
                ("charges_tip", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("starters", "Starters"),
                            ("mains", "Mains"),
                            ("sides", "Sides"),
                            ("desserts", "Desserts"),
                            ("alcohol", "Alcoholic drinks"),
                            ("soft", "Soft drinks"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(1), max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal(0), max_digits=12
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="quotes.menuitem",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="quotes.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "name"), name="unique_menu_item_per_restaurant"
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "number"),
                name="unique_quote_number_per_restaurant",
            ),
        ),
    ]
