# Generated by Django 5.1.15 on 2026-08-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Dates the event runs over, each one served in full",
            ),
        ),
    ]
