# Generated by Django 5.1.15 on 2026-08-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_quote_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteline",
            name="add_on",
            field=models.BooleanField(default=False),
        ),
    ]
