# Generated by Django 5.1.15 on 2026-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_quoteline_add_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
