# Generated by Django 5.1.15 on 2026-08-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_quote_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="show_quantities",
            field=models.BooleanField(default=True),
        ),
    ]
