# Generated by Django 5.1.15 on 2026-09-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_quote_show_quantities"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="manual_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost of one unit, for what the POS does not sell",
                max_digits=12,
                null=True,
            ),
        ),
    ]
