# Generated by Django 5.1.15 on 2026-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0006_menuitem_manual_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="venue",
            field=models.CharField(
                choices=[
                    ("in_house", "At the restaurant"),
                    ("off_site", "Event away from the restaurant"),
                    ("grill", "Grill away from the restaurant"),
                ],
                default="in_house",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="course",
            field=models.CharField(
                choices=[
                    ("starters", "Starters"),
                    ("mains", "Mains"),
                    ("sides", "Sides"),
                    ("desserts", "Desserts"),
                    ("alcohol", "Alcoholic drinks"),
                    ("soft", "Soft drinks"),
                    ("service", "Services"),
                    ("other", "Other"),
                ],
                default="starters",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quoteline",
            name="course",
            field=models.CharField(
                choices=[
                    ("starters", "Starters"),
                    ("mains", "Mains"),
                    ("sides", "Sides"),
                    ("desserts", "Desserts"),
                    ("alcohol", "Alcoholic drinks"),
                    ("soft", "Soft drinks"),
                    ("service", "Services"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
