# Generated by Django 5.1.15 on 2026-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0007_quote_venue_alter_menuitem_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("consumption", "By consumption"),
                    ("per_guest", "Price per guest"),
                ],
                default="per_guest",
                max_length=20,
            ),
        ),
    ]
