# Generated by Django 5.1.15 on 2026-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0008_alter_quote_pricing_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="availability",
            field=models.CharField(
                choices=[
                    ("both", "Anywhere"),
                    ("in_house", "At the restaurant only"),
                    ("off_site", "Away from the restaurant only"),
                ],
                default="both",
                max_length=20,
            ),
        ),
    ]
