# Generated by Django 5.1.15 on 2026-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_menuitem_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='prices_are_net',
            field=models.BooleanField(default=False, verbose_name='Prices do not include the consumption tax'),
        ),
    ]
