# Generated by Django 5.1.15 on 2026-09-29 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_importbatch_sale_import_batch"),
        ("tenants", "0003_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCovers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "guests",
                    models.PositiveIntegerField(help_text="People served that day."),
                ),
                (
                    "accounts",
                    models.PositiveIntegerField(help_text="Bills closed that day."),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_covers",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "daily covers",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("restaurant", "date"), name="unique_covers_per_day"
                    )
                ],
            },
        ),
    ]
