# Generated by Django 5.1.15 on 2026-09-29 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_dailycovers"),
        ("tenants", "0003_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "guests",
                    models.PositiveIntegerField(help_text="People served that day."),
                ),
                (
                    "accounts",
                    models.PositiveIntegerField(help_text="Bills closed that day."),
                ),
                (
                    "bar_sales",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "bar_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "kitchen_sales",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "kitchen_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_covers",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "daily summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="DailyCovers",
        ),
        migrations.AddConstraint(
            model_name="dailysummary",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "date"), name="unique_covers_per_day"
            ),
        ),
    ]
